test

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -23,6 +23,6 @@ jobs:
       - name: Debug echo
         run: |
           filename="MY_FILE.TXT"
-          echo "::error::Filename $filename doesn't match possible files"
-          exit 1
+          exit 1 || echo "::error::Filename $filename doesn't match possible files"
+          exit 0 || echo "return 0 "
 
